http:
  port: 8080
  write_timeout: 30 # Second unit
  read_timeout: 30 # Second unit

mysql:
  dsn: "root:root@tcp(localhost:13316)/isb"
  slow_log: slow.log
  slow_time: 300 # Millisecond unit
  max_idle_conn: 16
  max_open_conn: 100

postgres:

redis:
  addr: "localhost:6379"
  password: ""
  db: 0

email: